### PR TITLE
Added HardwareIDs for OpenPGP v3 cards

### PR DESCRIPTION
**Pull request by aberus**

### CODE REVIEW

**Comment by vletoux** [comment]
Can you confirm that you tested the modified inf file ?

I'm asking because you added a new CID_0031f573c00160009000 to match the new card.
However, the CID is matching part of the ATR.
3B,DA,18,FF,81,B1,FE,75,1F,03,**00,31,C5,73,C0,01,40,00,90,00**,0C

And in the registry section, there is no addition for a new card entry with a new ATR.
(or the ATR mask has to be modified)
Only the old ATR with a 0xff mask is present.

**Comment by vletoux** [comment]
I need a verbal confirm that you tested it.

Alternatively, did you look at the other project I made ?
https://github.com/vletoux/OpenPGP-CSP 
The compatibility with the v3 is better and it allows also to require a certificate from Windows (while the minidriver is read only)

**Comment by aberus** [comment]
I tested with Certutil and installed [OpenPGP-CSP](https://github.com/vletoux/OpenPGP-CSP), otherwise it does not show me the certificates in The Certificate Manager tool (Certmgr). 

image



Response from `certutil -scinfo` (Some data obfuscated):

```
certutil -scinfo
The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
  0: Alcor Micro USB Smart Card Reader 0
--- Reader: Alcor Micro USB Smart Card Reader 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Status: The card is available for use.
---   Card: OpenPGP Card v3 (via OpenPGP CSP)
---    ATR:
        3b da 18 ff 81 b1 fe 75  1f 03 00 31 f5 73 c0 01   ;......u...1.s..
        60 00 90 00 1c                                     `....


=======================================================
Analyzing card in reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP Card v3 (via OpenPGP CSP)
Provider = OpenPGP CSP
Key Container = *****

No AT_SIGNATURE cert retrieved for reader: Alcor Micro USB Smart Card Reader 0
Cannot open the AT_KEYEXCHANGE key for reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------
================ Certificate 1 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP Card v3 (via OpenPGP CSP)
Provider = OpenPGP CSP
Key Container = *****

Cannot open the AT_SIGNATURE key for reader: Alcor Micro USB Smart Card Reader 0
No AT_KEYEXCHANGE cert retrieved for reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------
================ Certificate 2 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP Card v3 (via OpenPGP CSP)
Provider = OpenPGP CSP
Key Container = ***** [Default Container]

Cannot open the AT_SIGNATURE key for reader: Alcor Micro USB Smart Card Reader 0
Serial Number: *****
Issuer: *****
 NotBefore: *****
 NotAfter: *****
Subject: *****
Non-root Certificate
Cert Hash(sha1): *****

Performing AT_KEYEXCHANGE public key matching test...

Public key from KeyProvInfo container:
Public Key Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.1 RSA (RSA_SIGN)
    Algorithm Parameters: NULL
Public Key Length: 2048 bits
Public Key: UnusedBits = 0
    *****

Public key from Cert:
Public Key Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.1 RSA (RSA_SIGN)
    Algorithm Parameters:
    05 00
Public Key Length: 2048 bits
Public Key: UnusedBits = 0
    *****
No AT_KEYEXCHANGE cert retrieved for reader: Alcor Micro USB Smart Card Reader 0
AIK KeyId(sha1): *****
AIK KeyId(sha256): *****
Serial Number: *****
Issuer: *****
 NotBefore: *****
 NotAfter: *****
Subject: *****
Non-root Certificate
Cert Hash(sha1): *****

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP Card v3 (via OpenPGP CSP)
Provider = OpenPGP KSP
Key Container = *****

No  cert retrieved for reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------
================ Certificate 1 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP Card v3 (via OpenPGP CSP)
Provider = OpenPGP KSP
Key Container = *****

No  cert retrieved for reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------
================ Certificate 2 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP Card v3 (via OpenPGP CSP)
Provider = OpenPGP KSP
Key Container = *****

Serial Number: *****
Issuer: *****
 NotBefore: *****
 NotAfter: *****
Subject: *****
Non-root Certificate
Cert Hash(sha1): *****

Performing  public key matching test...

Public key from KeyProvInfo container:
Public Key Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.1 RSA (RSA_SIGN)
    Algorithm Parameters: NULL
Public Key Length: 2048 bits
Public Key: UnusedBits = 0
    *****

Public key from Cert:
Public Key Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.1 RSA (RSA_SIGN)
    Algorithm Parameters:
    05 00
Public Key Length: 2048 bits
Public Key: UnusedBits = 0
    *****
No  cert retrieved for reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------

Done.
CertUtil: -SCInfo command completed successfully.
```

**Comment by vletoux** [comment]
you are modifying the minidriver.
The certificate should be displayed with certutil.
The certutil output you showed indicates that the CSP has been used, not the minidriver.

My test point was about the minidriver.

**Comment by aberus** [comment]
I uninstalled OpenPGP-CSP, fixed ATR in the inf file and run again `certutil -scinfo`, log below. No certs. 😟 
I was under impression that this minidriver supports v3 cards, base on this commit bf493fe. I only need a minidriver not full CSP/KSP, I prefer using gpg(sm) for writing on a card.

```
certutil -scinfo
The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
  0: Alcor Micro USB Smart Card Reader 0
--- Reader: Alcor Micro USB Smart Card Reader 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Status: The card is available for use.
---   Card: OpenPGP V3
---    ATR:
        3b da 18 ff 81 b1 fe 75  1f 03 00 31 f5 73 c0 01   ;......u...1.s..
        60 00 90 00 1c                                     `....


=======================================================
Analyzing card in reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP V3
Provider = Microsoft Base Smart Card Crypto Provider
Key Container = (null) [Default Container]

Cannot open the AT_SIGNATURE key for reader: Alcor Micro USB Smart Card Reader 0
Cannot open the AT_KEYEXCHANGE key for reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Alcor Micro USB Smart Card Reader 0
---   Card: OpenPGP V3
Provider = Microsoft Smart Card Key Storage Provider
Key Container = (null) [Default Container]

Cannot open the  key for reader: Alcor Micro USB Smart Card Reader 0

--------------===========================--------------

Done.
CertUtil: -SCInfo command completed successfully.
```

**Comment by vletoux** [comment]
You probably need to remove / add the driver again.

the commit seems now to be fine.

**Comment by aberus** [comment]
Thanks for taking the time to figure this out.

**Pull request merged**
